name: base_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.1+2

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  micro_core:
    git:
      url: https://github.com/jonathan1313/mfe_micro_core.git
      ref: v1.0.0

  micro_app_login:
    git:
      url: https://github.com/jonathan1313/mfe_micro_app_login.git
      ref: v1.0.1

  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
